name: Generate Snake

on:
  schedule: # every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Snake SVG
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Rakshit-gen
          outputs: dist/snake.svg

      - name: Push Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
